### ISSUE TITLE
Keep popup open when selecting start & end dates

### ISSUE THREAD

**Issue by Drumstix42** [y0c/react-datepicker#11]
**Is your feature request related to a problem? Please describe.**
It appears selecting a date range requires the user to select a start date, and then click again to select an end date.

**Describe the solution you'd like**
A nicer user experience would be to keep the popup open until both the start and end dates have been selected.

**Describe alternatives you've considered**
Check out something like the Google date picker for flights.google.com. The user is able to choose both dates as needed (and in this example the popup actually includes a "done" button). 

**Additional context**
I think it should probably be up to the developer to decide if the popup closes automatically or not in all states. So more configurable options is best. For example. keeping the popup open until the user decides to close it could be an option as well (like a Done button as exemplified via Google Flights mention above)

**Comment by y0c** [comment]
Thank you for leaving us an issue.
i 'will update it next release
