### ISSUE TITLE
Time formatting in DatePicker input.

### ISSUE THREAD

**Issue by web2wire** [y0c/react-datepicker#12]
I'm not sure if this is a bug or a feature request but I am having trouble formatting a datetime input.

**Is your feature request related to a problem? Please describe.**
Basically I need the time part of a datetime formatted in 24 hour format, and not AM/PM. I have updated the dateFormat parameter to include my desired format but the input shows the date formatted with that plus also the time repeated using the AM/PM format afterwards.  This sandbox illustrates the problem, https://codesandbox.io/s/l4oq8z505q

 **Describe the solution you'd like**
I think if the date format includes a time element then the time should not be displayed again. Either that or there needs to be separate timeFormat prop for the time picker. Likewise really there should probably be a calendarFormat or monthFormat prop for the calendar component since the default of 2019.03 is a strange and rarely used format in the UK and probably elsewhere. Neither the time or month formats appear to be 
affected by changing the locale.

**Comment by y0c** [comment]
Thank you leaving an issue.
I'm afraid I haven't been able to think about it in timeFormat of development. 
In the next version, i will add timeFormat and update it.

**Comment by y0c** [comment]
🏷 v1.0.0 Release !
