### ISSUE TITLE
Change Moment dependency to date-fns

### ISSUE THREAD

**Issue by y0c** [y0c/react-datepicker#14]
Moment.js dependency will be change due to bundle size issue

**Comment by xxyuk** [comment]
Day.Js is a nice alternative to me

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs

**Comment by y0c** [comment]
Thank you for your cooment! 
i will consider Day.js

**Comment by iamkun** [comment]
Just noticed this interesting topic from your PR https://github.com/iamkun/dayjs/pull/543

Is there anything I can help with this dependency replacement? 

And we can release all the changes in 1.8.12.

**Comment by y0c** [comment]
Thanks to your help, it's going well.
