### ISSUE TITLE
initialdate does not work. Within the range date picker

### ISSUE THREAD

**Issue by thxwelchs** [y0c/react-datepicker#15]
Is not initialdate an option to work with the range date picker?
My input is still empty.

```jsx
state = {
        startDate: moment().subtract(7, 'days'),
        endDate: moment(),
    }


                <RangeDatePicker
                locale={"ko"}
                initialStartDate={startDate.toDate()}
                initialEndDate={endDate.toDate()}
                onChange={this.handleDateChange}/>
```

**Comment by y0c** [comment]
Sorry, I think it's a bug.
I'll fix it and apply it to the next version.

**Comment by y0c** [comment]
You can check for updates in storybook!

**Comment by thxwelchs** [comment]
> You can check for updates in storybook!

I checked, Thanks!

**Comment by thxwelchs** [comment]
Sorry, it still does not work at 0.3.6 version. Could you check it?

This is forked link.
https://codesandbox.io/s/32r22wz6r6

**Comment by y0c** [comment]
Sorry, There was a mistake in patching and compiling.
Would you like to try again with versoin 0.3.7?

**Comment by y0c** [comment]
codesandbox link:
https://codesandbox.io/s/82w5vr4ox8

**Comment by thxwelchs** [comment]
> Sorry, There was a mistake in patching and compiling.
> Would you like to try again with versoin 0.3.7?

That is really cool. Thanks!
