### ISSUE TITLE
 Range where start and end day are the same

### ISSUE THREAD

**Issue by StaySharp0** [y0c/react-datepicker#23]
I would like to have a range with the same start and end dates in the RangeDatePicker.
But clicking on the same day did not change anything.

You can satisfy my requirements by changing the following in your code:
```javascript
public handleDateChange = (actions: PickerAction) => (date: moment.Moment) => {
...
if (!start) {
      startDate = date;
    } else {
      if (end) {
        startDate = date;
        endDate = undefined;
      } else {
//      Original
//      if (isDayAfter(date, start)) { 
         if (!isDayBefore(date, start)) {
          endDate = date;
        } else {
          startDate = date;
        }
      }
    }
...
}
```

**Comment by y0c** [comment]
Thank you for leaving me an issue.
I' ll fix it and all changes release in v1.0.0.
Do you need this feature quickly?

**Comment by StaySharp0** [comment]
I hope this feature will be updated soon. :) 👍

**Comment by y0c** [comment]
I'll leave comments when the release comes.

**Comment by y0c** [comment]
🏷v1.0.0 Release !
