### ISSUE TITLE
Set first day of the week

### ISSUE THREAD

**Issue by bulutfatih** [y0c/react-datepicker#41]
**Is your feature request related to a problem? Please describe.**
_Currently, the week starts from Sunday to Saturday in the calendar.
It would be better to have an option to set the first day of the week._

**Describe the solution you'd like**
_We can have a prop to define the first day._

Thanks!

**Comment by flo-l** [comment]
This is fixed by #46. If you set a locale where the first weekday is Monday (like en-GB), you'll get the expected result.

**Comment by bulutfatih** [comment]
@flo-l Thanks for your contribution!
